---
- name: Apache server installed
  hosts: node1
  become: yes
  tasks:
  - name: latest Apache version installed
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: Apache enabled and running
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started
      
  - name: copy web.html
    ansible.builtin.copy:
      content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4'] }}) has been customized by Ansible.\n"
      dest: /var/www/html/index.html